---
- hosts: webservers
  tasks:
     - name: Install NodeJS package
       apt: name={{ item }} state=latest 
       loop:
         - nodejs
         - unzip
         - npm
     
     - name: Copy NodeJS code on Application servers
       copy: src=artifact.zip dest=/tmp/artifact.zip remote_src=no


     - name: Extract Code
       unarchive: src=/tmp/artifact.zip dest=/opt/ remote_src=True


     - name: Run Node Install
       shell: |
        npm install 
        nohup npm run start &
       args:
         chdir:  /opt/SonarQubeNodeJS-master   
